{% set name = "aioitertools" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 620bd241acc0bbb9ec819f1ab215866871b4bbd1f73836a55f799200ee86950c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit-core >=3.8,<4
    - typing_extensions >=4.0
  run:
    - python >={{ python_min }}
    - typing_extensions >=4.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - aioitertools
    - aioitertools.tests

about:
  home: https://github.com/jreese/aioitertools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: asyncio version of the standard multiprocessing module
  description: |
    Implementation of itertools, builtins, and more for AsyncIO and mixed-type
    iterables.
  doc_url: https://github.com/jreese/aioitertools
  dev_url: https://github.com/jreese/aioitertools

extra:
  recipe-maintainers:
    - nehaljwani
